config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_scope :admin do
    get 'admin', :to => 'devise/sessions#new'
    authenticated :admin do
      root :to => 'admins#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'static#index', as: :unauthenticated_root
    end
  end

  resources :admins, only:[:show]
  namespace :admin do
    resources :videos
    resources :testimonials
    resources :products do
      resources :product_images
    end
  end
  root 'static#index'
  get 'static/index'
  get 'static/about'
  get 'static/contact'
  resources :products, only: [:index, :show]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_images
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/admin/product_images_controller.rb
class Admin::ProductImagesController < ApplicationController
	def new
		@product_image = ProductImage.new
	end

	def create
		@product_image = ProductImage.new(product_image_params)
		@product = Product.find(params[:product_id])
		@product_image.product = @product
		if @product_image.save
			redirect_to admin_product_path(@product)
		else
			render :new
		end
	end

	private

	def product_image_params
		product_image_strong_params = [:image]
		params.require(:product_image).permit(product_image_strong_params)
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@product_image = ProductImage.new
	end

	def new
		@product = Product.new()
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to admin_products_path
		else
			render :new
		end
	end

	private

	def product_params
		params.require(:product).permit(:title, :price, :description)
	end
end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@testimonials = Testimonial.all

	end

	def show
		@testimonial = Testimonial.find(params[:id])
	end

	def new
		@testimonial = Testimonial.new
	end

	def create
		@testimonial = Testimonial.new(testimonial_params)
		if @testimonial.save
			redirect_to admin_testimonial_path(@testimonial)
		else
			render 'new'
		end
	end

	def edit
		@testimonial = Testimonial.find(params[:id])
	end

	private

	def testimonial_params
		params.require(:testimonial).permit(:name, :city, :state, :content, :company)
	end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@videos = Video.all
	end

	def show
		
	end

	def new
		
	end

	def edit
		
	end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
	def show

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show

	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  	@imagebar = [
  		{
  			title: 'Ryno Wire Caddy',
  			ipath: 'index/rs_full_2.jpg'
  		},
  		{
  			title: 'Ryno Vise',
  			ipath: 'index/rs_full_4.jpg'
  		},
  		{
  			title: 'Ryno Vise',
  			ipath: 'index/rs_full_3.jpg'
  		}
  	]
  	@testimonials = Testimonial.all
  end

  def about
    @videos = Video.all
    @testimonials = Testimonial.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/admin/product_images/_form.html.haml
= form_for [:admin, :product, @product_image] do |f|
  = f.file_field :image
  = f.submit

app/views/admin/product_images/index.html.haml
%h1 Product Images Index

app/views/admin/product_images/new.html.haml
= form_for [:admin, :product, @product_image] do |f|
	= f.file_field :image
	= f.submit

app/views/admin/products/index.html.haml
.container
	.row.rs-row
		.col-xs-12
			%h1 Products
			.panel.panel-default
				.panel-heading.text-right
					=link_to "+ New Product", new_admin_product_path
				.panel-body
					%table.table
						%thead
							%tr
								%th
								%th Title
								%th Price
								%th View
								%th Edit
								%th Delete
						%tbody
							-@products.each do |p|
								%tr
									%td.admin-product-image-td
										-unless p.product_images.empty?
											= image_tag p.product_images[0].image, class: 'img-responsive admin-product-image'
									%td= p.title
									%td= p.price
									%td
										=link_to admin_product_path(p) do
											%span.glyphicon.glyphicon-eye-open
									%td
										=link_to edit_admin_product_path(p) do
											%span.glyphicon.glyphicon-pencil
									%td
										=link_to admin_product_path(p), method: :delete do
											%span.glyphicon.glyphicon-trash

app/views/admin/products/new.html.haml
.container
	.row.rs-row
		.col-xs-12
			.panel.panel-default
				.panel-heading
					%h1.panel-title
						="New Product"
				.panel-body
					=form_for [:admin, @product] do |f|
						.form-group
							=f.label :title
							=f.text_field :title, {class: 'form-control'}

						.form-group
							=f.label :price
							=f.text_field :price, {class: 'form-control'}
						.form-group
							=f.label :description
							=f.text_area :description, {class: 'form-control'}
						=f.submit class: 'btn btn-default'

	
	
	

app/views/admin/products/show.html.haml
%section.subheader.light-bg#product-section-1
	.container
		.row
			.col-xs-12.text-center
				%h1.dark-text
					=@product.title
				=image_tag 'rs-logo.png', alt: 'Ryno Stand Electrician Tools', class: 'subheader-text-img'
%section#product-show-section.light-bg
	.container
		- if admin_signed_in?
			.row
				.col-xs-12
					.pull-right
						=link_to edit_admin_product_path(@product) do
							%span.glyphicon.glyphicon-pencil
						=link_to admin_product_path(@product), method: :delete do
							%span.glyphicon.glyphicon-trash
		.row
			.col-xs-12.col-md-7
				-unless @product.product_images.empty?
					= image_tag @product.product_images[0].image, id: 'product-main-img', class: 'img-responsive'
					-@product.product_images.each do |i|
						= image_tag i.image, alt:'Ryno Vise Electrician Tools', class: 'thumb'
					.add-image-thumb{'data-toggle':'modal', 'data-target':'#add-product-image-modal'}
						%span.glyphicon.glyphicon-plus
			.col-xs-12.col-md-5
				%h2.dark-text= @product.title
				%h4.dark-text Description
				%p.dark-text= @product.description
				%p.lead.dark-text= "$#{@product.price}"
.modal.fade#add-product-image-modal{tabindex:'-1', role:'dialog', 'aria-labelledby':'add-product-image-label'}
	.modal-dialog{role:'document'}
		.modal-content.light-bg
			.modal-header
				%button.close{type:'button', 'data-dismiss':'modal', 'aria-label':'Close'}
					%span{'aria-hidden':'true'} &times;
				%h4.modal-title#add-product-image-label
					Upload New Image
			.modal-body
				= form_for [:admin, @product, @product_image] do |f|
					.form-group
						= f.label :image, 'New Image'
						= f.file_field :image
					.form-group
						= f.submit 'Upload', class: 'btn btn-default'

app/views/admin/testimonials/_form.html.haml
=form_for [:admin, @testimonial] do |f|
	.form-group
		=f.label :name
		=f.text_field :name, {class: 'form-control'}
	.form-group
		=f.label :city
		=f.text_field :city, {class: 'form-control'}
	.form-group
		=f.label :state
		=f.text_field :state, {class: 'form-control'}
	.form-group
		=f.label :content
		=f.text_area :content, {class: 'form-control', rows: '5'}
	.form-group
		=f.label :company
		=f.text_field :company, {class: 'form-control'}
	=f.submit class: 'btn btn-default'

app/views/admin/testimonials/edit.html.haml
.container
	.row
		.col-xs-12
			.panel.panel-default
				.panel-heading
					%h1.panel-title
						="Edit Testimonial"
				.panel-body
					= render 'form'

app/views/admin/testimonials/index.html.haml
.container
	.row.rs-row
		.col-xs-12
			%h1 Testimonials
			.panel.panel-default
				.panel-heading.text-right
					=link_to "+New Testimonial", new_admin_testimonial_path
				.panel-body
					%table.table
						%thead
							%tr
								%th Company
								%th Name
								%th City, State
								%th View
								%th Edit
								%th Delete
						%tbody
							-@testimonials.each do |t|
								%tr
									%td= t.company
									%td= t.name
									%td= "#{t.city}, #{t.state}"
									%td
										=link_to admin_testimonial_path(t) do
											%span.glyphicon.glyphicon-eye-open
									%td
										=link_to edit_admin_testimonial_path(t) do
											%span.glyphicon.glyphicon-pencil
									%td
										=link_to admin_testimonial_path(t), method: :delete do
											%span.glyphicon.glyphicon-trash

app/views/admin/testimonials/new.html.haml
.container
	.row
		.col-xs-12
			.panel.panel-default
				.panel-heading
					%h1.panel-title
						="New Testimonial"
				.panel-body
					= render 'form'

app/views/admin/testimonials/show.html.haml
.container
	.row.rs-row
		.col-xs-12
			%h1 Testimonial
			.panel.panel-default
				.panel-heading.text-right
					=link_to edit_admin_testimonial_path(@testimonial) do
						%span.glyphicon.glyphicon-pencil
					=link_to admin_testimonial_path(@testimonial), method: :delete do
						%span.glyphicon.glyphicon-trash
				%ul.list-group
					%li.list-group-item
						%strong Company:
						= @testimonial.company
					%li.list-group-item
						%strong Name:
						= @testimonial.name
					%li.list-group-item
						%strong City, State:
						= "#{@testimonial.city}, #{@testimonial.state}"
					%li.list-group-item
						%strong Content:
						= @testimonial.content

app/views/admin/videos/index.html.haml
.container
	.row.rs-row
		.col-xs-12
			%h1 Videos
			.panel.panel-default
				.panel-heading.text-right
					=link_to "+ New Video", new_admin_video_path
				.panel-body
					-@videos.each_slice(3) do |x, y, z|
						.row.video-row
							-[x,y,z].each do |video|
								-if video
									.col-xs-12.col-md-4.video-col
										.embed-responsive.embed-responsive-16by9
											%iframe{:src=>"#{video.url}", 'allowfullscreen'=>'true'}
										.video-controls
											=link_to admin_video_path(video), method: :delete, class: 'btn btn-danger pull-right' do
												%span{class: 'glyphicon glyphicon-trash', 'aria-hidden'=>'true'}
												Delete

app/views/admins/show.html.haml
%h1
	="Admin show"

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title RynoStand
		%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		-if flash[:notice]
			%p{class:"notice"}
				=notice
		-if flash[:error]
			%p{class:"alert"}
				=alert
		= render 'shared/nav'
		= yield

app/views/products/index.html.haml
%section.subheader#product-section-1.light-bg
	.container
		.row
			.col-xs-12.text-center
				%h1.dark-text Products
				= image_tag 'rs-logo.png', {alt:'Ryno Stand Electrician Tools', class:'subheader-text-img'}

%section#packages-section.light-bg
	.container
		.row
			.col-xs-12
				%h1.dark-text Packages
		-@products.each_slice(3) do |x, y, z|
			.row.product-row
				-[x,y,z].each do |p|
					-if p
						.col-xs-12.col-sm-6.col-md-4.text-center
							.thumbnail
								.caption
									%h3.dark-text
										= p.title
									%p.lead.dark-text
										= p.price
									= link_to 'View', product_path(p), class: 'dark-clear-btn'

app/views/shared/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-static-top
	.container
		.navbar-header
			%button.navbar-toggle.collapsed{type: 'button', data:{toggle: 'collapse', target:'#rs-collapse'}}
				%span.sr-only
					='Toggle Navigation'
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			=link_to 'Brink Industries', root_url, class: 'navbar-brand'
		.collapse.navbar-collapse#rs-collapse
			%ul.nav.navbar-nav.navbar-right
				- if admin_signed_in?
					%li.dropdown
						= link_to root_path, {class: 'dropdown-toggle', data:{toggle: 'dropdown'}, role: 'button', aria:{haspopup:'true', expanded: false}}do
							Pages
							%span.caret
						%ul.dropdown-menu
							%li= link_to 'Home', static_index_path
							%li= link_to 'About', static_about_path
							%li= link_to 'Contact', static_contact_path
					%li= link_to 'Products', admin_products_path
					%li= link_to 'Testimonials', admin_testimonials_path
					%li= link_to 'Videos', admin_videos_path
					%li.dropdown
						= link_to root_path, {class: 'dropdown-toggle', data:{toggle: 'dropdown'}, role: 'button', aria:{haspopup:'true', expanded: false}}do
							%span.glyphicon.glyphicon-user
							%span.caret
						%ul.dropdown-menu
							%li= link_to 'Sign In',  new_admin_session_path
							%li= link_to 'Sign Out', destroy_admin_session_path, method: :delete
				-else
					%li= link_to 'Home', root_url
					%li= link_to 'About', static_about_path
					%li= link_to 'Products', products_path
					%li= link_to 'Contact', static_contact_path